### ISSUE TITLE
编译出现“奇奇怪怪的符号”的三种解决方案

### ISSUE THREAD

**Issue by dugu9sword** [java-b/Lab-0#2]
有同学反映在执行 `javac HelloWorld.java` 的时候，出现一堆奇怪的字母，这是字符集不匹配导致的。怎么理解“字符集”的问题呢？
假设，上帝创造了这个东西：
![image](https://cloud.githubusercontent.com/assets/6239743/18353410/73a21350-7614-11e6-8cd6-ec35468788c2.png)
中国人叫他——“足球”
英国人叫他——“football”
美国人叫他——“soccer”
那么问题来了，一个中国人在英国人面前说“足球”，英国人知道他指的是足球吗？
问题就出在这里。
计算机上的文字有若干种“编码方式”——可以理解为不同的“语言”。每个“物体”都有一种“编号”来表示。同样的汉字“我”在一种编码（UTF8编码）下是E68891，在另一种编码（GBK）下是CED2，这样的话，我们要尽量避免用一种编码去解析另一种编码——也就是避免在俄罗斯人面前说中文。

怎么解决呢？

三种方法：
**第一种，让俄罗斯人知道我是中国人，让他用中文来理解，比如用谷歌翻译。**
**第二种，说俄语。**
**第三种，使用双方都能理解的语言，比如阿拉伯数字。俄罗斯人来中国超市买东西，指着一个足球，然后售货员伸出3根手指意思是这个3块钱，交易成功。**

同样的，在我们的编写代码的过程中，有两个步骤：
**第一步，在atom里编写代码**
**第二步，用javac编译代码**
然而，有时候我们的“编辑器”（比如Atom）的“语言”，和“编译器”（比如javac）的“语言”是不一样的。好比编辑器说了一段中文，但是编译器以为编辑器说的是俄语，那就出现“乱码”了。

想想看，你看到俄罗斯语言是不是以为是乱码？这里我们遇到问题的同学，一般来说编辑器（atom）采取的是utf8编码，但是呢，编译器（javac）采取的是GBK编码，两个不符合，就懵逼了。

那么怎么解决？

第一种，让编译器（javac）知道我们用编辑器（atom）写出来的代码是UTF8，告诉他，兄弟，我是UTF8，虽然我知道你默认是说GBK的语言，但是你想理解我的话，得用我的语言。
因此，在编译时，我们不采取 `javac HelloWorld.java`，而是采取 `javac -encoding UTF8 HelloWorld.java`，如图，看是不是解决了？
（虽然编译通过了，但马赛克部分是我敲代码出现了笔误，请谅解）
![qq 20160908224725](https://cloud.githubusercontent.com/assets/6239743/18353867/3dc62ac6-7616-11e6-979a-ab87160f7eb9.png)

第二种，告诉编辑器（atom），兄弟，人家编译器（javac）是俄罗斯人，他们说的语言是GBK（类比俄语），我们想交流不能用UTF8（类比中文）。咋整？咱也用GBK吧！他就理解了。
点击右下角的“UTF8”，
![qq 20160908225008](https://cloud.githubusercontent.com/assets/6239743/18354263/7c0fdd76-7617-11e6-9cdc-683e6f7a1a0f.png)

在弹出的窗口中输入gbk，然后点击GBK选项
![qq 20160908225029](https://cloud.githubusercontent.com/assets/6239743/18354269/804f313e-7617-11e6-95ec-23adfdf149cf.png)

然后你就可以愉快地按照原来 Lab-0 的要求去写代码、编译、运行了。

第三种，更加粗暴，删掉那行中文注释就行了（我检验下来是可以成功的）。
总的来说，英语是世界语言，全球通行的，一般来说会英语大部分情况下都是勉强可行的，换句话说，UTF8和GBK都能认识英语部分，而在对汉字部分的理解不同。你是俄罗斯人，不懂中文，但是我们都懂英文，行行行，我不说中文不就行了？

**Comment by dugu9sword** [comment]
写不动了，来个人验证下我的胡言乱语

**Comment by ddagym** [comment]
哇看起来好厉害鼓掌鼓掌

**Comment by SEEKFORONE** [comment]
强

**Comment by Mrss10044** [comment]
好形象
